MPJDOCBOOK-59 - Upgrade from 2.2.3 to 2.3.0 gives java.lang.NoClassDefFoundError: com/icl/saxon/TransformerFactoryImpl
git-svn-id: https://svn.jboss.org/repos/maven/plugins/jdocbook/maven-jdocbook-plugin/trunk@504 144b0f12-573d-0410-b250-8e3534f3c584